/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sszk2' at '17/10/21 7:08' with Gradle 2.14.1
 *
 * @author sszk2, @date 17/10/21 7:08
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
